/* Phase 4 — generality proof.
 * A brand-new spec (specs/example-app-env.form.yaml), nothing like config-forge,
 * renders + exports through the unchanged engine. Proves the renderer is
 * spec-driven, not special-cased to its two seed use cases. */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ctx = { module: { exports: {} }, console };
vm.runInNewContext(readFileSync(join(ROOT, "engine.js"), "utf8"), ctx);
const E = ctx.module.exports;
const spec = E.parseEnvelope(E.parseSpecText(readFileSync(join(ROOT, "specs", "example-app-env.form.yaml"), "utf8")).data);

test("proof spec validates as a form", () => {
  assert.equal(spec.kind, "form");
  assert.equal(spec.meta.name, "webapp-env");
  assert.equal(E.validateEnvelope(spec).length, 0);
});

test("env export: default banner, public fields, group order, defaults as strings", () => {
  const env = E.formExportEnv(spec.spec, {});
  assert.match(env, /^# generated by spec-renderer from spec 'webapp-env'/); // generic default banner, not config-forge's
  assert.match(env, /NODE_ENV=production/);
  assert.match(env, /PORT=3000/);
  assert.match(env, /HOST=0\.0\.0\.0/);
  assert.match(env, /DATABASE_URL=""/); // empty default -> quoted empty
  // secrets are NOT in the public env
  assert.doesNotMatch(env, /SESSION_SECRET=/);
  assert.doesNotMatch(env, /JWT_SECRET=/);
});

test("secrets routed to the secrets export", () => {
  const sec = E.formExportSecrets(spec.spec, {}, "secret");
  assert.match(sec, /SESSION_SECRET=/);
  assert.match(sec, /JWT_SECRET=/);
  assert.doesNotMatch(sec, /\nPORT=/);
});

test("json export: public only, 2-space, trailing newline", () => {
  const json = E.formExportJson(spec.spec, {});
  const obj = JSON.parse(json);
  assert.equal(obj.PORT, "3000"); // integer-typed field, value kept as a string
  assert.equal(obj.DATABASE_URL, "");
  assert.equal("SESSION_SECRET" in obj, false);
  assert.equal(json.endsWith("\n"), true);
});

test("validation honors the new schema (format + required + enum)", () => {
  const fields = Object.fromEntries(E.formFields(spec.spec).map((f) => [f.key, f]));
  assert.equal(E.formFieldError(fields.DATABASE_URL, ""), "required");          // fill, required
  assert.match(E.formFieldError(fields.DATABASE_URL, "not-a-url"), /must be/);   // format: uri
  assert.equal(E.formFieldError(fields.DATABASE_URL, "https://x/y"), null);
  assert.match(E.formFieldError(fields.HOST, "999.1.1.1"), /octets/);            // ipv4 octet range
  assert.match(E.formFieldError(fields.ADMIN_EMAIL, "nope"), /email/);           // format: email
  assert.match(E.formFieldError(fields.NODE_ENV, "staging"), /one of/);          // enum membership
});
